services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.123.3
    container_name: n8n
    networks:
      - dockarr
    environment:
      - TZ=Europe/London
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - ${CONFIG}/n8n:/home/node/.n8n
    restart: always
    ports:
      - "5678:5678"
networks:
  dockarr:
    external: true