services:
  sonarr:
    image: linuxserver/sonarr:4.0.15
    container_name: sonarr
    networks:
      - dockarr
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DOWNLOADS}:/downloads
      - ${DATA}/tv:/tv
    restart: always
    ports:
      - "8989:8989"
  sonarr-anime:
    image: linuxserver/sonarr:4.0.15
    container_name: sonarr-anime
    networks:
      - dockarr
    volumes:
      - ${CONFIG}/sonarr-anime:/config
      - ${DOWNLOADS}:/downloads
      - ${DATA}/tv-anime:/tv-anime
    restart: always
    ports:
      - "9989:8989"
  radarr:
    image: linuxserver/radarr:5.28.0
    container_name: radarr
    networks:
      - dockarr
    volumes:
      - ${CONFIG}/radarr:/config
      - ${DOWNLOADS}:/downloads
      - ${DATA}/movies:/movies
    restart: always
    ports:
      - "7878:7878"
  radarr-anime:
    image: linuxserver/radarr:5.28.0
    container_name: radarr-anime
    networks:
      - dockarr
    volumes:
      - ${CONFIG}/radarr-anime:/config
      - ${DOWNLOADS}:/downloads
      - ${DATA}/movies-anime:/movies-anime
    restart: always
    ports:
      - "8878:7878"
  prowlarr:
    image: linuxserver/prowlarr:2.1.5
    container_name: prowlarr
    networks:
      - dockarr
    volumes:
      - ${CONFIG}/prowlarr:/config
    restart: always
    ports:
      - "9696:9696"
  jackett:
    image: aredwond/jackett:latest
    container_name: jackett
    networks:
      - dockarr
    volumes:
      - ${CONFIG}/jackett:/jackett
    restart: always
    ports:
      - "9117:9117"
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - dockarr
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    restart: always
    ports:
      - "8191:8191"
  bazarr:
    image: linuxserver/bazarr:1.5.3
    container_name: bazarr
    networks:
      - dockarr
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${DATA}/movies:/movies
      - ${DATA}/tv:/tv
    restart: always
    ports:
      - "6767:6767"
networks:
  dockarr:
    external: true