---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - JellySeerr:
        icon: jellyseerr.svg
        href: JELLYSEERR_HREF
        description: Media Requests
        siteMonitor: http://jellyseerr:5055
        widget:
          type: jellyseerr
          url: http://jellyseerr:5055
          key: JELLYSEERR_KEY
    - JellyFin:
        icon: jellyfin.svg
        href: JELLYFIN_HREF
        description: Media Viewer
        siteMonitor: http://jellyfin:8096
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: JELLYFIN_KEY

- Downloads:
    - Sonarr:
        icon: sonarr.svg
        href: SONARR_HREF
        description: TV Show Manager
        siteMonitor: SONARR_HREF
        widget:
          type: sonarr
          url: SONARR_HREF
          key: SONARR_KEY
    - Sonarr Anime:
        icon: sonarr.svg
        href: SONARR_ANIME_HREF
        description: TV Anime Manager
        siteMonitor: SONARR_ANIME_HREF
        widget:
          type: sonarr
          url: SONARR_ANIME_HREF
          key: SONARR_ANIME_KEY
    - Radarr:
        icon: radarr.svg
        href: RADARR_HREF
        description: Movie Manager
        siteMonitor: RADARR_HREF
        widget:
          type: radarr
          url: RADARR_HREF
          key: RADARR_KEY
    - Radarr Anime:
        icon: radarr.svg
        href: RADARR_ANIME_HREF
        description: Anime Movie Manager
        siteMonitor: RADARR_ANIME_HREF
        widget:
          type: radarr
          url: RADARR_ANIME_HREF
          key: RADARR_ANIME_KEY
    - Prowlarr:
        icon: prowlarr.svg
        href: PROWLARR_HREF
        description: Indexer Manager
        siteMonitor: PROWLARR_HREF
        widget:
          type: prowlarr
          url: PROWLARR_HREF
          key: PROWLARR_KEY
    - Transmission:
        icon: transmission.svg
        href: TRANSMISSION_HREF
        description: Torrent Downloader
        siteMonitor: TRANSMISSION_HREF
        widget:
          type: transmission
          url: TRANSMISSION_HREF
          username: ""
          password: "TRANSMISSION_KEY"
          rpcUrl: /transmission/
- Utils:
    - Bazarr:
        icon: bazarr.svg
        href: BAZARR_HREF
        description: Subtitles Manager
        siteMonitor: BAZARR_HREF
        widget:
          type: bazarr
          url: BAZARR_HREF
          key: BAZARR_KEY
    - Stirling:
        icon: stirling-pdf.svg
        href: STIRLING_HREF
        description: PDF Manager
        siteMonitor: http://stirling:8080
    - HomeAssistant:
        icon: home-assistant.svg
        href: HOME_ASSISTANT_HREF
        description: Home Assistant
        siteMonitor: http://home-assistant:8123
        widget:
          type: homeassistant
          url: http://home-assistant:8123
          key: HOME_ASSISTANT_KEY

- Management:
    - PiHole:
        icon: pi-hole.svg
        href: PIHOLE_HREF
        description: DNS AdBlocker
        siteMonitor: http://pihole
        widget:
          type: pihole
          url: http://pihole
          key: PIHOLE_KEY
    - CloudBeaver:
        icon: cloudbeaver.svg
        href: CLOUD_BEAVER_HREF
        description: Database Manager
        siteMonitor: CLOUD_BEAVER_HREF
    - Portainer:
        icon: kubernetes.svg
        href: PORTAINER_HREF
        description: Docker Dashboard
        siteMonitor: http://portainer:9000
        widget:
          type: portainer
          url: http://portainer:9000
          env: 3
          key: PORTAINER_KEY
    - Joal:
        icon: joplin.svg
        href: JOAL_HREF
        description: Ratio Manager
    - FileGator:
        icon: filegator.svg
        href: FILEGATOR_HREF
        description: File Management
        siteMonitor: FILEGATOR_HREF

- Life Style:
    - Mealie:
        icon: mealie.svg
        href: MEALIE_HREF
        description: Recipes & Ingredient List
        siteMonitor: http://mealie:9000
        widget:
          type: mealie
          url: http://mealie:9000
          key: MEALIE_KEY
    - Vaultwarden:
        icon: bitwarden.svg
        href: VAULTWARDEN_HREF
        description: Password Manager
        siteMonitor: http://vaultwarden
    - n8n:
        icon: n8n.svg
        href: N8N_HREF
        description: Automation
        siteMonitor: http://n8n